(function () {
  function $(id) { return document.getElementById(id); }
  function on(el, evt, cb) { if (el) el.addEventListener(evt, cb); }
  function init() {
    try { if ('serviceWorker' in navigator) { window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js')); } } catch(_){}

    const tabButtons = document.querySelectorAll('.tab-btn');
    const panels = document.querySelectorAll('.tab-panel');
    function showTab(name){ tabButtons.forEach(b=>{ const a=(b.dataset.tab===name); b.classList.toggle('active',a); b.setAttribute('aria-selected', a?'true':'false'); }); panels.forEach(p=>p.classList.toggle('active', p.id===name)); }
    tabButtons.forEach(btn=> on(btn,'click', ()=> showTab(btn.dataset.tab)));
    showTab('payments');

    const ledgerSelects = { payment: $('payment-ledger'), paymentsFilter: $('payments-filter-ledger'), recv: $('recv-ledger'), recvFilter: $('recv-filter-ledger'), stock: $('stock-ledger'), dashboard: $('dash-ledger') };

    function refreshLedgers(){ const ledgers = Store.getLedgers(); Object.values(ledgerSelects).forEach(sel=>{ if(!sel) return; const cur=sel.value; sel.innerHTML=''; if(sel===ledgerSelects.paymentsFilter||sel===ledgerSelects.recvFilter){ const o=document.createElement('option'); o.value='All'; o.textContent='All'; sel.appendChild(o);} for(const l of ledgers){ const o=document.createElement('option'); o.value=l; o.textContent=l; sel.appendChild(o);} if(cur && Array.from(sel.options).some(o=>o.value===cur)) sel.value=cur; }); const list=$('ledger-list'); if(list){ list.innerHTML=''; ledgers.forEach(l=>{ const s=document.createElement('span'); s.className='pill'; s.textContent=l; list.appendChild(s); }); } }

    on($('add-ledger-btn'),'click', ()=>{ const name=$('new-ledger-name')?.value; const res=Store.addLedger(name); if(!res.ok){ alert(res.msg); return;} if($('new-ledger-name')) $('new-ledger-name').value=''; refreshLedgers(); refreshDashboard(); refreshPaymentsTable(); refreshReceivables(); refreshStockTable(); });

    refreshLedgers();

    const creditFields=$('credit-fields'), debitFields=$('debit-fields');
    document.querySelectorAll('input[name="pay-kind"]').forEach(r => on(r,'change', ()=>{ if(!r.checked) return; const v=r.value; if(creditFields) creditFields.classList.toggle('hidden', v!=='credit'); if(debitFields) debitFields.classList.toggle('hidden', v!=='debit'); }));

    on($('add-credit-btn'),'click', ()=>{ const ledger=ledgerSelects.payment?.value; const date= ($('payment-date')?.value || new Date().toISOString().slice(0,10)); const name=$('credit-name')?.value.trim(); const paymentType=$('credit-type')?.value; const amount=Number($('credit-amount')?.value); if(!ledger){ alert('Select a ledger'); return;} if(!amount){ alert('Enter amount'); return;} Store.addCredit({ date,name,paymentType,amount,ledger }); if($('credit-name')) $('credit-name').value=''; if($('credit-amount')) $('credit-amount').value=''; refreshPaymentsTable(); refreshDashboard(); });

    on($('add-debit-btn'),'click', ()=>{ const ledger=ledgerSelects.payment?.value; const date= ($('payment-date')?.value || new Date().toISOString().slice(0,10)); const invoiceType=$('debit-invoice-type')?.value.trim(); const invoiceNumber=$('debit-invoice-number')?.value.trim(); const amount=Number($('debit-amount')?.value); if(!ledger){ alert('Select a ledger'); return;} if(!amount){ alert('Enter amount'); return;} Store.addDebit({ date,invoiceType,invoiceNumber,amount,ledger }); if($('debit-invoice-type')) $('debit-invoice-type').value=''; if($('debit-invoice-number')) $('debit-invoice-number').value=''; if($('debit-amount')) $('debit-amount').value=''; refreshPaymentsTable(); refreshDashboard(); });

    const paymentsFilter=ledgerSelects.paymentsFilter; on(paymentsFilter,'change', refreshPaymentsTable);
    function naira(n){ return new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',minimumFractionDigits:2}).format(Number(n||0)); }

    function refreshPaymentsTable(){ const ledger=paymentsFilter?.value || 'All'; const rows=Store.listPayments(ledger); const wrap=$('payments-table'); if(!wrap) return; let html='<table><thead><tr><th>Date</th><th>Type</th><th>Details</th><th>Ledger</th><th>Amount</th><th></th></tr></thead><tbody>'; for(const r of rows){ const details=(r.type==='credit')?`${r.name||''} · ${r.paymentType||''}`:`${r.invoiceType||''} · #${r.invoiceNumber||''}`; html+=`<tr><td>${r.date||''}</td><td>${r.type}</td><td>${details}</td><td>${r.ledger}</td><td>${naira(r.amount)}</td><td><button class="danger" data-del="${r.id}">Delete</button></td></tr>`; } html+='</tbody></table>'; wrap.innerHTML=html; wrap.querySelectorAll('button[data-del]').forEach(btn=> on(btn,'click', ()=>{ if(confirm('Delete entry?')){ Store.deletePayment(btn.dataset.del); refreshPaymentsTable(); refreshDashboard(); } })); let totalCredits=0,totalDebits=0; if(ledger==='All'){ for(const r of rows){ if(r.type==='credit') totalCredits+=Number(r.amount||0); else totalDebits+=Number(r.amount||0);} } else { const t=Store.paymentsTotals(ledger); totalCredits=t.credits; totalDebits=t.debits; } const bal=totalDebits-totalCredits; const elC=$('payments-total-credits'), elD=$('payments-total-debits'), elB=$('payments-balance'); if(elC) elC.textContent=naira(totalCredits); if(elD) elD.textContent=naira(totalDebits); if(elB){ elB.textContent=naira(bal); elB.style.color = bal>0 ? '#22c55e' : bal<0 ? '#ef4444' : '#e5e7eb'; } }

    on($('export-ledger-csv'),'click', ()=>{ const ledger=(paymentsFilter?.value==='All'||!paymentsFilter?.value)?ledgerSelects.payment?.value:paymentsFilter?.value; if(!ledger){ alert('Select a ledger to export'); return;} const rows=Store.listPayments(ledger); const header=['Date','Type','Payment Name/Invoice Type','Payment Type/Invoice #','Ledger','Amount']; const lines=[header.join(',')]; for(const r of rows){ if(r.type==='credit') lines.push([r.date,'Credit',(r.name||''),(r.paymentType||''),r.ledger,r.amount].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')); else lines.push([r.date,'Debit',(r.invoiceType||''),(r.invoiceNumber||''),r.ledger,r.amount].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')); } const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8;'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`ledger_${ledger}_statement.csv`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); });

    // Receivables
    const RECV_PAGE_SIZE=10; let recvPage=1;
    on($('add-recv-btn'),'click', ()=>{ const ledger=ledgerSelects.recv?.value; const date=($('recv-date')?.value || new Date().toISOString().slice(0,10)); const customer=$('recv-customer')?.value.trim(); const invoiceNumber=$('recv-invnum')?.value.trim(); const amount=Number($('recv-amount')?.value); const comment=$('recv-comment')?.value.trim(); if(!ledger){ alert('Select a ledger'); return;} if(!customer){ alert('Enter customer'); return;} if(!amount){ alert('Enter amount'); return;} Store.addReceivable({ date,customer,invoiceNumber,amount,comment,ledger }); if($('recv-customer')) $('recv-customer').value=''; if($('recv-invnum')) $('recv-invnum').value=''; if($('recv-amount')) $('recv-amount').value=''; if($('recv-comment')) $('recv-comment').value=''; refreshReceivables(); refreshDashboard(); });

    on(ledgerSelects.recvFilter,'change', ()=>{ recvPage=1; refreshReceivables(); });
    function refreshReceivables(){ const ledger=ledgerSelects.recvFilter?.value || 'All'; const full=Store.listReceivables(ledger); const wrap=$('receivables-table'); if(!wrap) return; const totalAmt=full.reduce((s,r)=>s+Number(r.amount||0),0); const totalEl=$('receivables-total'); if(totalEl) totalEl.textContent=`Total: ${naira(totalAmt)}`; const totalPages=Math.max(1, Math.ceil(full.length/RECV_PAGE_SIZE)); if(recvPage>totalPages) recvPage=totalPages; const start=(recvPage-1)*RECV_PAGE_SIZE; const rows=full.slice(start,start+RECV_PAGE_SIZE); let html='<table><thead><tr><th>Date</th><th>Customer</th><th>Invoice #</th><th>Ledger</th><th>Amount</th><th>Comment</th><th></th><th></th></tr></thead><tbody>'; for(const r of rows){ html+=`<tr><td>${r.date||''}</td><td>${r.customer||''}</td><td>${r.invoiceNumber||''}</td><td>${r.ledger}</td><td>${naira(r.amount)}</td><td>${r.comment||''}</td><td><button class="outline" data-edit="${r.id}">Edit</button></td><td><button class="danger" data-del="${r.id}">Delete</button></td></tr>`; } html+='</tbody></table>'; wrap.innerHTML=html; wrap.querySelectorAll('button[data-del]').forEach(btn=> on(btn,'click', ()=>{ if(confirm('Delete receivable?')){ Store.deleteReceivable(btn.dataset.del); refreshReceivables(); refreshDashboard(); } })); wrap.querySelectorAll('button[data-edit]').forEach(btn=> on(btn,'click', ()=> openEditModal(btn.dataset.edit))); const prev=$('recv-prev'), next=$('recv-next'), info=$('recv-page-info'); if(prev&&next&&info){ info.textContent=`Page ${recvPage}/${totalPages}`; prev.disabled=recvPage<=1; next.disabled=recvPage>=totalPages; prev.onclick=()=>{ if(recvPage>1){ recvPage--; refreshReceivables(); } }; next.onclick=()=>{ if(recvPage<totalPages){ recvPage++; refreshReceivables(); } }; } refreshFavouriteSections(); }

    on($('export-recv-csv'),'click', ()=>{ const ledger=ledgerSelects.recvFilter?.value || 'All'; const rows=Store.listReceivables(ledger); const header=['Date','Customer','Invoice #','Ledger','Amount','Comment']; const lines=[header.join(',')]; for(const r of rows){ lines.push([r.date, r.customer||'', r.invoiceNumber||'', r.ledger, r.amount, r.comment||''].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')); } const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8;'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`receivables_${ledger}.csv`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); });

    function renderFavourites(){ const favWrap=$('fav-customers'); if(!favWrap) return; favWrap.innerHTML=''; for(const name of Store.getFavourites()){ const span=document.createElement('span'); span.className='pill'; span.textContent=name+' '; const btn=document.createElement('button'); btn.className='danger'; btn.textContent='×'; btn.style.marginLeft='.5rem'; on(btn,'click', ()=>{ Store.removeFavourite(name); renderFavourites(); refreshFavouriteSections(); }); span.appendChild(btn); favWrap.appendChild(span);} }
    on($('add-fav-btn'),'click', ()=>{ const name=$('new-fav-name')?.value; const res=Store.addFavourite(name); if(!res.ok){ alert(res.msg); return;} if($('new-fav-name')) $('new-fav-name').value=''; renderFavourites(); refreshFavouriteSections(); });

    function refreshFavouriteSections(){ const FAV_PAGE_SIZE=10; window.__favPages=window.__favPages||{}; const favs=Store.getFavourites(); const box=$('fav-recv-container'); if(!box) return; box.innerHTML=''; if(favs.length===0){ box.innerHTML='<p class="small">No favourites yet. Add up to 5 customers to track their receivables separately.</p>'; return;} const all=Store.listReceivables('All'); for(const name of favs){ if(!(name in window.__favPages)) window.__favPages[name]=1; const allRows=all.filter(r=>r.customer===name); const totalPages=Math.max(1, Math.ceil(allRows.length/FAV_PAGE_SIZE)); if(window.__favPages[name]>totalPages) window.__favPages[name]=totalPages; const start=(window.__favPages[name]-1)*FAV_PAGE_SIZE; const rows=allRows.slice(start,start+FAV_PAGE_SIZE); let html=`<div class="card" style="margin:.5rem 0"><h4>${name}</h4><div class="table">`; if(rows.length===0){ html+='<p class="small">No receivables yet.</p>'; } else { html+='<table><thead><tr><th>Date</th><th>Invoice #</th><th>Ledger</th><th>Amount</th><th>Comment</th></tr></thead><tbody>'; for(const r of rows){ html+=`<tr><td>${r.date||''}</td><td>${r.invoiceNumber||''}</td><td>${r.ledger}</td><td>${naira(r.amount)}</td><td>${r.comment||''}</td></tr>`; } html+='</tbody></table>'; } const total=allRows.reduce((s,r)=>s+Number(r.amount||0),0); html+=`<div class=\"pill\" style=\"margin-top:.5rem\">Total: ${naira(total)}</div>`; html+=`<div class=\"row wrap\" style=\"margin-top:.5rem\"><span class=\"small\">Page ${window.__favPages[name]}/${totalPages}</span><div style=\"margin-left:auto; display:flex; gap:.5rem\"><button class=\"outline\" data-favprev=\"${name}\">Prev</button><button class=\"outline\" data-favnext=\"${name}\">Next</button></div></div>`; html+='</div></div>'; const div=document.createElement('div'); div.innerHTML=html; box.appendChild(div); const prevBtn=div.querySelector(`button[data-favprev=\"${name}\"]`); const nextBtn=div.querySelector(`button[data-favnext=\"${name}\"]`); on(prevBtn,'click', ()=>{ if(window.__favPages[name]>1){ window.__favPages[name]--; refreshFavouriteSections(); } }); on(nextBtn,'click', ()=>{ if(window.__favPages[name]<totalPages){ window.__favPages[name]++; refreshFavouriteSections(); } }); }
    }

    // Edit modal
    let editingId=null;
    function openEditModal(id){ editingId=id; const modal=$('edit-modal'); const ledgerSel=$('edit-ledger'); if(!modal||!ledgerSel) return; ledgerSel.innerHTML=''; for(const l of Store.getLedgers()){ const o=document.createElement('option'); o.value=l; o.textContent=l; ledgerSel.appendChild(o);} const it=Store.listReceivables('All').find(r=>r.id===id); if(!it) return; if($('edit-date')) $('edit-date').value = it.date || new Date().toISOString().slice(0,10); if($('edit-customer')) $('edit-customer').value = it.customer || ''; if($('edit-invnum')) $('edit-invnum').value = it.invoiceNumber || ''; if($('edit-amount')) $('edit-amount').value = Number(it.amount||0); if($('edit-comment')) $('edit-comment').value = it.comment || ''; ledgerSel.value = it.ledger; modal.classList.remove('hidden'); }
    window.openEditModal = openEditModal;
    function closeEditModal(){ const m=$('edit-modal'); if(m) m.classList.add('hidden'); editingId=null; }
    on($('edit-cancel'),'click', closeEditModal);
    on($('edit-save'),'click', ()=>{ if(!editingId) return; const fields={ date:$('edit-date')?.value || new Date().toISOString().slice(0,10), customer:$('edit-customer')?.value.trim(), invoiceNumber:$('edit-invnum')?.value.trim(), amount:Number($('edit-amount')?.value||0), comment:$('edit-comment')?.value.trim(), ledger:$('edit-ledger')?.value }; if(!fields.customer){ alert('Enter customer'); return;} Store.updateReceivable(editingId, fields); closeEditModal(); refreshReceivables(); refreshDashboard(); });

    // Stock
    const productSelect=$('stock-product');
    function populateProducts(){ const products=Store.listProducts(); if(!productSelect) return; productSelect.innerHTML=''; for(const [name,price] of Object.entries(products)){ const opt=document.createElement('option'); opt.value=name; opt.textContent=name; opt.dataset.price=price; productSelect.appendChild(opt);} syncPriceFromProduct(); }
    function syncPriceFromProduct(){ const sel=productSelect?.options[productSelect.selectedIndex]; if($('stock-price')) $('stock-price').value = sel?.dataset?.price || 0; }
    on(productSelect,'change', syncPriceFromProduct);

    function refreshStockTable(){ const ledger=ledgerSelects.stock?.value; const items=ledger?Store.getStockForLedger(ledger):[]; const wrap=$('stock-table'); if(!wrap) return; let html='<table><thead><tr><th>Product</th><th>Price (₦)</th><th>Qty</th><th>Value</th></tr></thead><tbody>'; for(const it of items){ html+=`<tr><td>${it.name}</td><td>${naira(it.price)}</td><td>${it.qty}</td><td>${naira(it.value)}</td></tr>`; } html+='</tbody></table>'; wrap.innerHTML=html; const total=items.reduce((s,x)=>s+x.value,0); const tot=$('stock-total'); if(tot) tot.textContent=`Total Value: ${naira(total)}`; refreshDashboard(); }
    on($('add-stock-btn'),'click', ()=>{ const ledger=ledgerSelects.stock?.value; const product=productSelect?.value; const price=Number($('stock-price')?.value); const qty=Number($('stock-qty')?.value); if(!ledger){ alert('Select a ledger'); return;} if(!product){ alert('Select a product'); return;} Store.setStock(ledger,product,price,qty); if($('stock-qty')) $('stock-qty').value=''; refreshStockTable(); });

    // Dashboard
    function refreshDashboard(){ const ledger=ledgerSelects.dashboard?.value || Store.getLedgers()[0]; const {credits,debits}=Store.paymentsTotals(ledger); const recv=Store.receivablesTotal(ledger); const stock=Store.stockTotalValue(ledger); const profit=(credits+recv+stock)-debits; if($('stat-debits')) $('stat-debits').textContent=naira(debits); if($('stat-credits')) $('stat-credits').textContent=naira(credits); if($('stat-recv')) $('stat-recv').textContent=naira(recv); if($('stat-stock')) $('stat-stock').textContent=naira(stock); const w=$('business-worth'); if(w){ w.textContent=naira(profit); w.style.background='#6b7280'; w.style.color= profit>0?'#22c55e': profit<0?'#ef4444':'#ffffff'; } }
    on(ledgerSelects.dashboard,'change', refreshDashboard); on(ledgerSelects.stock,'change', refreshStockTable);

    populateProducts(); refreshLedgers();
    if(ledgerSelects.payment?.options.length>0) ledgerSelects.payment.selectedIndex=0;
    if(ledgerSelects.paymentsFilter?.options.length>0) ledgerSelects.paymentsFilter.selectedIndex=0;
    if(ledgerSelects.recv?.options.length>0) ledgerSelects.recv.selectedIndex=0;
    if(ledgerSelects.recvFilter?.options.length>0) ledgerSelects.recvFilter.selectedIndex=0;
    if(ledgerSelects.stock?.options.length>0) ledgerSelects.stock.selectedIndex=0;
    if(ledgerSelects.dashboard?.options.length>0) ledgerSelects.dashboard.selectedIndex=0;
    refreshPaymentsTable(); refreshStockTable(); refreshDashboard();
  }

  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded', init); else init();

  window.addEventListener('error', (e)=>{ try{ const n=document.createElement('div'); n.style.cssText='position:fixed;bottom:8px;left:8px;right:8px;background:#7f1d1d;color:#fff;padding:8px 10px;border-radius:8px;z-index:9999;font:12px system-ui'; n.textContent='Error: '+(e.error?.message||e.message||'Unknown'); document.body.appendChild(n); setTimeout(()=>n.remove(), 6000);}catch(_){}} ,{once:true});
})();
